name: Release

on:
  push:
    branches:
      - "main"
      - "develop"
  workflow_dispatch:

jobs:
  release:
    if: ${{ github.repository_owner == 'blaxel-templates' }}
    uses: blaxel-templates/workflows/.github/workflows/release.yaml@main
    with:
      environment: ${{ github.ref_name == 'main' && 'prod' || 'dev' }}
      repository: ${{ github.repository }}
      sha: ${{ github.sha }}
    secrets:
      BL_ADMIN_USERNAME_DEV: ${{ secrets.BL_ADMIN_USERNAME_DEV }}
      BL_ADMIN_PASSWORD_DEV: ${{ secrets.BL_ADMIN_PASSWORD_DEV }}
      BL_ADMIN_USERNAME_PROD: ${{ secrets.BL_ADMIN_USERNAME_PROD }}
      BL_ADMIN_PASSWORD_PROD: ${{ secrets.BL_ADMIN_PASSWORD_PROD }}
